import mongoose from 'mongoose';
import dotenv from 'dotenv';
import GameType from '../models/GameType';

dotenv.config();

const gameTypes = [
  // MASA VE TAŞ OYUNLARI
  {
    name: '101 Okey',
    slug: '101-okey',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: true,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Okey',
    slug: 'okey',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: true,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Tavla',
    slug: 'tavla',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 2,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'both',
    expectsFee: false,
    defaultDuration: 30,
    isActive: true,
  },
  {
    name: 'Tabu',
    slug: 'tabu',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 4,
    maxPlayers: 12,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: true,
    equipmentDescription: 'Tabu oyun kartları',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 60,
    isActive: true,
  },
  {
    name: 'Monopoly',
    slug: 'monopoly',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 6,
    hasTeams: false,
    requiresEquipment: true,
    equipmentDescription: 'Monopoly oyun seti',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 120,
    isActive: true,
  },
  {
    name: 'Scrabble',
    slug: 'scrabble',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: false,
    requiresEquipment: true,
    equipmentDescription: 'Scrabble oyun seti',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 60,
    isActive: true,
  },
  {
    name: 'Jenga',
    slug: 'jenga',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 2,
    maxPlayers: 8,
    hasTeams: false,
    requiresEquipment: true,
    equipmentDescription: 'Jenga blokları',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 30,
    isActive: true,
  },
  {
    name: 'Catan',
    slug: 'catan',
    category: 'masa_tas',
    icon: 'dice',
    minPlayers: 3,
    maxPlayers: 4,
    hasTeams: false,
    requiresEquipment: true,
    equipmentDescription: 'Catan oyun seti',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 90,
    isActive: true,
  },

  // SPOR VE FİZİKSEL AKTİVİTELER
  {
    name: 'Halısaha',
    slug: 'halisaha',
    category: 'spor',
    icon: 'soccer',
    minPlayers: 4,
    maxPlayers: 14,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: false,
    venueType: 'outdoor',
    expectsFee: true,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Basketbol',
    slug: 'basketbol',
    category: 'spor',
    icon: 'basketball',
    minPlayers: 2,
    maxPlayers: 10,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: false,
    venueType: 'both',
    expectsFee: false,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Voleybol',
    slug: 'voleybol',
    category: 'spor',
    icon: 'volleyball',
    minPlayers: 4,
    maxPlayers: 12,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: false,
    venueType: 'both',
    expectsFee: false,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Tenis',
    slug: 'tenis',
    category: 'spor',
    icon: 'tennis',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: true,
    teamAssignmentOptions: ['manual'],
    requiresEquipment: true,
    equipmentDescription: 'Tenis raketi',
    venueType: 'both',
    expectsFee: true,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Masa Tenisi',
    slug: 'masa-tenisi',
    category: 'spor',
    icon: 'table-tennis',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: true,
    teamAssignmentOptions: ['manual'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 60,
    isActive: true,
  },

  // BECERİ OYUNLARI
  {
    name: 'Bilardo 8 Top',
    slug: 'bilardo-8-top',
    category: 'beceri',
    icon: 'pool',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: true,
    teamAssignmentOptions: ['manual'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: true,
    defaultDuration: 60,
    isActive: true,
  },
  {
    name: 'Bilardo Amerikan',
    slug: 'bilardo-amerikan',
    category: 'beceri',
    icon: 'pool',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: true,
    teamAssignmentOptions: ['manual'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: true,
    defaultDuration: 60,
    isActive: true,
  },
  {
    name: 'Bowling',
    slug: 'bowling',
    category: 'beceri',
    icon: 'bowling',
    minPlayers: 1,
    maxPlayers: 6,
    hasTeams: true,
    teamAssignmentOptions: ['manual'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: true,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Dart',
    slug: 'dart',
    category: 'beceri',
    icon: 'target',
    minPlayers: 2,
    maxPlayers: 8,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 45,
    isActive: true,
  },
  {
    name: 'Satranç',
    slug: 'satranc',
    category: 'beceri',
    icon: 'chess',
    minPlayers: 2,
    maxPlayers: 2,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'both',
    expectsFee: false,
    defaultDuration: 60,
    isActive: true,
  },

  {
    name: 'Uno',
    slug: 'uno',
    category: 'masa_tas',
    icon: 'cards',
    minPlayers: 2,
    maxPlayers: 10,
    hasTeams: false,
    requiresEquipment: true,
    equipmentDescription: 'Uno kartları',
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 45,
    isActive: true,
  },

  // KART OYUNLARI
  {
    name: 'Batak',
    slug: 'batak',
    category: 'kart',
    icon: 'cards',
    minPlayers: 4,
    maxPlayers: 4,
    hasTeams: true,
    teamAssignmentOptions: ['manual', 'random'],
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 60,
    isActive: true,
  },
  {
    name: 'Kral',
    slug: 'kral',
    category: 'kart',
    icon: 'cards',
    minPlayers: 4,
    maxPlayers: 6,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 90,
    isActive: true,
  },
  {
    name: 'Blöf',
    slug: 'blof',
    category: 'kart',
    icon: 'cards',
    minPlayers: 2,
    maxPlayers: 6,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 45,
    isActive: true,
  },
  {
    name: 'Pişti',
    slug: 'pisti',
    category: 'kart',
    icon: 'cards',
    minPlayers: 2,
    maxPlayers: 4,
    hasTeams: false,
    requiresEquipment: false,
    venueType: 'indoor',
    expectsFee: false,
    defaultDuration: 30,
    isActive: true,
  },
];

const seedGameTypes = async () => {
  try {
    console.log('MongoDB bağlantısı kuruluyor...');
    const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI || '';
    if (!mongoUri) {
      throw new Error('MONGODB_URI veya MONGO_URI environment variable tanımlanmamış!');
    }
    await mongoose.connect(mongoUri);
    console.log('MongoDB bağlandı!');

    console.log('Mevcut oyun tipleri temizleniyor...');
    await GameType.deleteMany({});

    console.log('Yeni oyun tipleri ekleniyor...');
    await GameType.insertMany(gameTypes);

    console.log(`✅ ${gameTypes.length} oyun tipi başarıyla eklendi!`);

    mongoose.connection.close();
    console.log('Bağlantı kapatıldı.');
  } catch (error: any) {
    console.error('❌ Hata:', error.message);
    process.exit(1);
  }
};

seedGameTypes();

